name: ipywidget_docs
channels:
- conda-forge
- defaults
dependencies:
- ipykernel
- jinja2
- jupyter_sphinx
- ipywidgets
- nbformat
- nbsphinx
- notebook>=4.2
- python=3.6
- sphinx>=1.4.6
- sphinx_rtd_theme
- tornado
- python-dateutil
- recommonmark
- matplotlib==2.1.2
- numpy==1.14.0
- Cython==0.27.3
- scipy==1.0.0