channels:
- conda-forge
dependencies:
- jupyterlab=0.34.0
- nodejs=8.9
- notebook=5.6
- nbconvert=5.3
- ipykernel=4.7
- ipywidgets=7.3
- ipyleaflet=0.9
- widgetsnbextension=3.3
- matplotlib=2.1
- pandas=0.20
- python=3.6
- scikit-image=0.13
- scikit-learn=0.19
- tensorflow=1.1
- sympy=1.0
